services:
  zephir-api:
    build:
      context: .
      target: production
    command: ["python", "-m", "gunicorn", "--log-level", "{$LOG_LEVEL:-INFO}", "-b", "0.0.0.0:${APP_PORT:-8000}", "app:create_app()"]
    ports:
      - "${APP_PORT-8000}:${APP_PORT-8000}"
    environment:
      # Required
      - FLASK_ENV
      - APP_PORT
      - LOG_LEVEL

      # One of the following must be set
      - DATABASE_URI

      - DATABASE_CREDENTIALS_SECRET_NAME
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - DB_DATABASE
    depends_on:
      - test
  test:
    build:
      context: .
      target: test