template:
  path: ecs.yaml.j2
  type: file

dependencies:
  - "{{ sceptre_user_data.environment }}/ecr.yaml"
  - "{{ sceptre_user_data.environment }}/logging.yaml"
  - "{{ sceptre_user_data.environment }}/network.yaml"

parameters:
  ContainerName: "{{ sceptre_user_data.resource_name_prefix }}-container"
  {% if var.image_tag | default(False) -%}
  ImageTag: "{{ var.image_tag }}"
  {% else -%}
  ImageTag: latest
  {% endif %}

  VPCID: !stack_output_external cdl-d2d-prd-vpc-stack::vpc
  SubnetIDs:
    - !stack_output_external cdl-d2d-prd-defaultsubnet-stack::defaultsubnet2a
    - !stack_output_external cdl-d2d-prd-defaultsubnet-stack::defaultsubnet2b
    - !stack_output_external cdl-d2d-prd-defaultsubnet-stack::defaultsubnet2c

  LoadBalancerSecurityGroupID: !stack_output "{{ sceptre_user_data.environment }}/network.yaml::LoadBalancerSecurityGroupID"
  TargetGroupARN: !stack_output "{{ sceptre_user_data.environment }}/network.yaml::TargetGroupARN"

  RepositoryURI: !stack_output "{{ sceptre_user_data.environment }}/ecr.yaml::RepositoryURI"
  RepositoryARN: !stack_output "{{ sceptre_user_data.environment }}/ecr.yaml::RepositoryARN"

  LogGroupID: !stack_output "{{ sceptre_user_data.environment }}/logging.yaml::LogGroupID"
  LogGroupArn: !stack_output "{{ sceptre_user_data.environment }}/logging.yaml::LogGroupArn"

  ApplicationPort: "{{ sceptre_user_data.port }}"

  FlaskEnvironment: production
  LogLevel: INFO

  DatabaseCredentialsSecretName: /d2d/zephir/api/prd/database
  DatabaseSecurityGroupID: sg-0e60820fecb39e7f4
