template:
  path: ecs.yaml
  type: file

dependencies:
  - prd/ecr.yaml
  - prd/logging.yaml
  - prd/network.yaml

parameters:
  ECSServiceSecurityGroupName: "{{ base_name }}-{{ environment }}-ecs-service-security-group"
  ECSClusterName: "{{ base_name }}-{{ environment }}-ecs-cluster"
  ContainerName: "{{ base_name }}-{{ environment }}-container"
  TaskDefinitionFamilyName: "{{ base_name }}-{{ environment }}-ecs-task-definition"
  ECSTaskRoleName: "{{ base_name }}-{{ environment }}-ecs-task-role"
  ECSTaskExecutionRoleName: "{{ base_name }}-{{ environment }}-ecs-task-execution-role"
  ECSServiceName: "{{ base_name }}-{{ environment }}-ecs-service"
  {% if var.image_tag | default(False) %}
  ImageTag: "{{ var.image_tag }}"
  {% else %}
  ImageTag: latest
  {% endif %}
  
  VPCID: !stack_output_external cdl-d2d-prd-vpc-stack::vpc
  SubnetIDs:
    - !stack_output_external cdl-d2d-prd-defaultsubnet-stack::defaultsubnet2a
    - !stack_output_external cdl-d2d-prd-defaultsubnet-stack::defaultsubnet2b
    - !stack_output_external cdl-d2d-prd-defaultsubnet-stack::defaultsubnet2c

  LoadBalancerSecurityGroupID: !stack_output prd/network.yaml::LoadBalancerSecurityGroupID
  TargetGroupARN: !stack_output prd/network.yaml::TargetGroupARN

  RepositoryURI: !stack_output prd/ecr.yaml::RepositoryURI
  RepositoryARN: !stack_output prd/ecr.yaml::RepositoryARN
  
  LogGroupID: !stack_output prd/logging.yaml::LogGroupID
  LogGroupArn: !stack_output prd/logging.yaml::LogGroupArn

  ApplicationPort: "8000"
  
  FlaskEnvironment: production
  LogLevel: INFO

  DatabaseCredentialsSecretName: /d2d/zephir/api/prd/database
  DatabaseSecurityGroupID: sg-0e60820fecb39e7f4
