template:
  path: waf.yaml.j2
  type: file

dependencies:
  - "{{ sceptre_user_data.environment }}/network.yaml"

parameters:
  LoadBalancerArn: !stack_output "{{ sceptre_user_data.environment }}/network.yaml::LoadBalancerARN"
