template:
  path: autoscaling.yaml
  type: file

dependencies:
  - dev/ecs.yaml

parameters:
  # ECSAutoScalingPlanName: "{{ base_name }}-{{ environment }}-ecs-auto-scaling-plan"
  ECSClusterName: !stack_output dev/ecs.yaml::ECSClusterName
  ECSServiceName: !stack_output dev/ecs.yaml::ECSServiceName

  ECSCloudFormationStackARN: !stack_output dev/ecs.yaml::ECSCloudFormationStackARN

  MinCapacity: "1"
  MaxCapacity: "3"