profile: cdl-d2d-dev

sceptre_user_data:
  environment: dev
  resource_name_prefix: "{{ sceptre_user_data.program }}-{{ sceptre_user_data.service }}-{{ sceptre_user_data.subservice }}-dev"
  url_authority: "{{ sceptre_user_data.program }}-{{ sceptre_user_data.service }}-{{ sceptre_user_data.subservice }}-dev.d2ddev.cdlib.net"

stack_tags:
  # Use !stack_attr instead of jinja syntax because "environment" is defined in same template.
  # The resolver !stack_attr executes after jinja.
  Environment: !stack_attr sceptre_user_data.environment
