template:
  path: autoscaling.yaml
  type: file

dependencies:
  - stg/ecs.yaml

parameters:
  # ECSAutoScalingPlanName: "{{ sceptre_user_data.resource_name_prefix }}-ecs-auto-scaling-plan"
  ECSClusterName: !stack_output stg/ecs.yaml::ECSClusterName
  ECSServiceName: !stack_output stg/ecs.yaml::ECSServiceName

  ECSCloudFormationStackARN: !stack_output stg/ecs.yaml::ECSCloudFormationStackARN

  MinCapacity: "1"
  MaxCapacity: "3"