template:
  path: waf.yaml
  type: file

dependencies:
  - stg/network.yaml

parameters:
  WebACLName: "{{ base_name }}-{{ environment }}-waf-webacl"
  WebACLMetricName: "{{ base_name }}-{{ environment }}-waf-webacl-metric"
  LoadBalancerArn: !stack_output stg/network.yaml::LoadBalancerARN
