name: CI

on:
  push:
    branches:
      - github-ci

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.x

    - name: Display Python version
      run: |
        python --version

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev

    - name: Run tests with coverage
      run: |
        poetry run pytest --cov=app --cov-report=term-missing
      continue-on-error: false  

    - name: Run Bandit for security analysis
      run: |
        poetry run bandit -r app
      continue-on-error: false  

    - name: Run Ruff for linting
      run: |
        poetry run ruff check .
      continue-on-error: false 

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.4.0

    - name: Build current Docker image with tests
      run: |
        docker build --target test -t zephir-api2:test .
