name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - '**'

jobs:
  CI:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca  # v3.9.0 
      # update w/ git ls-remote https://github.com/docker/setup-buildx-action.git | grep refs/tags/v

    - name: Build current Docker image with tests
      run: |
        docker build --target test -t zephir-api2:test .
