name: Code Analysis

permissions:
  contents: read

on:
  push:
    branches:
      - '**'

jobs:
  CodeAnalysis:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Display Python version
      run: |
        uv run python --version

    - name: Install dependencies
      run: |
        uv sync --frozen

    - name: Check for outdated dependencies
      if: env.skip-job != 'true'
      run: |
        uv tree --outdated

    - name: Run tests with coverage in latest stable 3.x
      run: |
        uv run pytest --cov=app --cov-report=term-missing
      continue-on-error: false  

    - name: Run Bandit for security analysis
      run: |
        uv run bandit -r app
      continue-on-error: false  

    - name: Run Ruff for linting
      run: |
        uv run ruff check .
      continue-on-error: false 

    - name: Run Vulture for dead code analysis
      run: |
        uv run vulture . --min-confidence 70
      continue-on-error: false 

