name: Compatibility Matrix

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  CompatibilityMatrix:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13', '3.14.0-alpha.5']
        update-strategy: [minor, major]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get Python version
      id: python_version
      run: |
        uv run python --version

    - name: Backup lock file
      run: |
        if [ -f uv.lock ]; then
          mv uv.lock uv.lock.backup
        fi

    - name: Install and update dependencies
      run: |
        if [[ "${{ matrix.update-strategy }}" == "minor" ]]; then
          echo "Updating to minor versions"
          uv lock --upgrade
          uv sync
        elif [[ "${{ matrix.update-strategy }}" == "major" ]]; then
          echo "Updating to major versions"
          cp pyproject.toml pyproject.toml.backup
          sed -i 's/~=/>=/g' pyproject.toml  # Adjust constraints to allow major updates
          uv lock --upgrade
          uv sync
          mv pyproject.toml.backup pyproject.toml
        fi

    - name: Restore lock file
      run: |
        if [ -f uv.lock.backup ]; then
          mv uv.lock.backup uv.lock
        fi

    - name: Run tests
      run: |
        uv run pytest
      continue-on-error: false  # Set to true if you want to continue on test failures
