name: Matrix

on:
  push:
    branches:
      - 'extend-matrix'
  workflow_dispatch:

jobs:
  Matrix:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image-tag: ['3.12-slim-bullseye', '3.13.0rc1', '3.13.0rc1-slim', 'latest']
        update-strategy: [locked-install, unlocked-install, latest-install]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.4.0

  
    - name: Install and update dependencies
      run: |
        echo "Image tag: ${{ matrix.image-tag }}"
        echo "Update strategy: ${{ matrix.update-strategy }}"

        if [[ "${{ matrix.update-strategy }}" == "locked-install" ]]; then
        
        echo "Running normal test with updated dependencies"
        docker build --no-cache --build-arg IMAGE_TAG=${{ matrix.image-tag }} --target test -t zephir-api2:test .

        elif [[ "${{ matrix.update-strategy }}" == "unlocked-install" ]]; then
        
        echo "Running normal test with updated dependencies"
        docker build --no-cache --build-arg IMAGE_TAG=${{ matrix.image-tag }} --target build-unlocked-test -t zephir-api2:test .

        elif [[ "${{ matrix.update-strategy }}" == "latest-install" ]]; then
        
        echo "Running normal test with updated dependencies"
        docker build --no-cache --build-arg IMAGE_TAG=${{ matrix.image-tag }} --target build-latest-test -t zephir-api2:test .

        fi