name: Docker Matrix

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  DockerMatrix:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        image-tag: ['3.13-slim-bullseye', '3.14-rc-bullseye']
        update-strategy: [default, minor]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca  # v3.9.0 
      # update w/ git ls-remote https://github.com/docker/setup-buildx-action.git | grep refs/tags/v

    - name: Build current Docker image with tests
      run: |
        docker build --target test -t zephir-api2:test .
    
    - name: Install and update dependencies
      run: |
        if [[ "${{ matrix.update-strategy }}" == "default" ]]; then
        
        echo "Running normal test suite"
        docker build --build-arg IMAGE_TAG=${{ matrix.image-tag }} --target test -t zephir-api2:test .
        
        elif [[ "${{ matrix.update-strategy }}" == "minor" ]]; then
        
        echo "Minor version update"
        docker build --build-arg IMAGE_TAG=${{ matrix.image-tag }} --target test-minor-update -t zephir-api2:test .

        fi
